# Generated by Django 2.2.6 on 2019-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred',
            field=models.ManyToManyField(blank=True, related_name='fans', to='AnswerQuest.Question'),
        ),
    ]
