# Generated by Django 2.2.6 on 2019-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='starred',
        ),
        migrations.AddField(
            model_name='user',
            name='starred_questions',
            field=models.ManyToManyField(blank=True, related_name='Qfans', to='AnswerQuest.Question'),
        ),
    ]
