# Generated by Django 2.2.6 on 2019-10-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0003_auto_20191029_2043'),
        ('AnswerQuest', '0003_auto_20191029_2033'),
    ]

    operations = [
    ]
