# Generated by Django 2.2.6 on 2019-11-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0005_user_starred_answer'),
        ('AnswerQuest', '0005_user_starred_answers'),
    ]

    operations = [
    ]
