# Generated by Django 2.2.6 on 2019-10-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0004_auto_20191030_0148'),
        ('AnswerQuest', '0006_auto_20191030_1407'),
    ]

    operations = [
    ]
