# Generated by Django 2.2.6 on 2019-11-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0006_merge_20191103_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='starred_answer',
        ),
    ]
