# Generated by Django 2.2.6 on 2019-10-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0007_auto_20191030_1439'),
        ('AnswerQuest', '0005_auto_20191030_1439'),
    ]

    operations = [
    ]
