# Generated by Django 2.2.6 on 2019-10-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0007_auto_20191030_1439'),
        ('AnswerQuest', '0004_auto_20191030_0148'),
    ]

    operations = [
    ]
