# Generated by Django 2.2.6 on 2019-10-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0003_auto_20191029_2120'),
        ('AnswerQuest', '0007_auto_20191030_1439'),
    ]

    operations = [
    ]
